// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTN9zSJxG3I6z6fqaS5ioTmo6bT7zUz3g',
    appId: '1:357639930035:web:18b7bc1629c81ddc32f0c6',
    messagingSenderId: '357639930035',
    projectId: 'skypro-courese',
    authDomain: 'skypro-courese.firebaseapp.com',
    storageBucket: 'skypro-courese.firebasestorage.app',
    measurementId: 'G-MSVE4YVSRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1zh8AfbffKi2L7HAzHY0_wJifpzYxyQ',
    appId: '1:357639930035:android:3c18944366858e3632f0c6',
    messagingSenderId: '357639930035',
    projectId: 'skypro-courese',
    storageBucket: 'skypro-courese.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKX120BVmZ9MehGRYY23dCVesEBFdotEs',
    appId: '1:357639930035:ios:069a8e9db08bd95832f0c6',
    messagingSenderId: '357639930035',
    projectId: 'skypro-courese',
    storageBucket: 'skypro-courese.firebasestorage.app',
    iosBundleId: 'com.example.skypro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKX120BVmZ9MehGRYY23dCVesEBFdotEs',
    appId: '1:357639930035:ios:069a8e9db08bd95832f0c6',
    messagingSenderId: '357639930035',
    projectId: 'skypro-courese',
    storageBucket: 'skypro-courese.firebasestorage.app',
    iosBundleId: 'com.example.skypro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTN9zSJxG3I6z6fqaS5ioTmo6bT7zUz3g',
    appId: '1:357639930035:web:db40fd686556831232f0c6',
    messagingSenderId: '357639930035',
    projectId: 'skypro-courese',
    authDomain: 'skypro-courese.firebaseapp.com',
    storageBucket: 'skypro-courese.firebasestorage.app',
    measurementId: 'G-V0ZGYW6YK7',
  );

}